---
title: "Curso R básico"
author: "Rossana Torres Alvarez"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(downloadthis)
knitr::opts_chunk$set(echo = TRUE)
```

# Notas de clase

## Clase 1. Introducción a R, R Studio y conceptos básicos de programación en R
*	Ventajas de usar R
*	Interfaces gráficas disponibles
*	Introducción al lenguaje de programación

```{r, echo=FALSE}
download_link(
  link = "https://github.com/rossanatorres/Rbasico/blob/main/slides/clase1.pdf",
  button_label = "Descargar clase1.pdf",
  button_type = "primary",
  has_icon = TRUE,
  icon = "fa fa-save",
  self_contained = FALSE
)
```


```{r, echo=FALSE}
download_link(
  link = "https://github.com/rossanatorres/Rbasico/blob/main/labs/lab1.R",
  button_label = "Descargar lab1.R",
  button_type = "info",
  has_icon = TRUE,
  icon = "fa fa-save",
  self_contained = FALSE
)
```

```{r, echo=FALSE}
download_link(
  link = "https://github.com/rossanatorres/Rbasico/blob/main/hw/hw1.docx",
  button_label = "Descargar tarea1.R",
  button_type = "warning",
  has_icon = TRUE,
  icon = "fa fa-save",
  self_contained = FALSE
)
```


## Clase 2.	Importación/exportación/manejo de datos
*	Cómo importar/exportar datos
*	Introducción al uso de paqueterías
*	Introducción a tidyverse


# Tareas resueltas



# Archivos



